# Generated by Django 4.0 on 2022-01-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_passenger_othername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='otherName',
        ),
    ]
