# Generated by Django 4.0 on 2022-01-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_driver_othername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='serialNumber',
            field=models.PositiveIntegerField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
