# Generated by Django 4.0 on 2022-01-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_driver_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='serialNumber',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
